/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArchiveCard: typeof import('./components/shared/archive/ArchiveCard.vue')['default']
    ArchiveClient: typeof import('./components/shared/archive/ArchiveClient.vue')['default']
    ArchiveGroup: typeof import('./components/shared/archive/ArchiveGroup.vue')['default']
    Button: typeof import('./components/ui/button/Button.vue')['default']
    Card: typeof import('./components/shared/archive/card.vue')['default']
    Field: typeof import('./components/ui/field/Field.vue')['default']
    FieldContent: typeof import('./components/ui/field/FieldContent.vue')['default']
    FieldDescription: typeof import('./components/ui/field/FieldDescription.vue')['default']
    FieldError: typeof import('./components/ui/field/FieldError.vue')['default']
    FieldGroup: typeof import('./components/ui/field/FieldGroup.vue')['default']
    FieldLabel: typeof import('./components/ui/field/FieldLabel.vue')['default']
    FieldLegend: typeof import('./components/ui/field/FieldLegend.vue')['default']
    FieldSeparator: typeof import('./components/ui/field/FieldSeparator.vue')['default']
    FieldSet: typeof import('./components/ui/field/FieldSet.vue')['default']
    FieldTitle: typeof import('./components/ui/field/FieldTitle.vue')['default']
    Group: typeof import('./components/shared/archive/group.vue')['default']
    HealthStatus: typeof import('./components/shared/health/HealthStatus.vue')['default']
    Input: typeof import('./components/ui/input/Input.vue')['default']
    Label: typeof import('./components/ui/label/Label.vue')['default']
    Link: typeof import('./components/shared/Link.vue')['default']
    Marquee: typeof import('./components/shared/Marquee.vue')['default']
    MobileMenu: typeof import('./components/shared/navigation/MobileMenu.vue')['default']
    RequestForm: typeof import('./components/shared/forms/RequestForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/ui/select/Select.vue')['default']
    SelectContent: typeof import('./components/ui/select/SelectContent.vue')['default']
    SelectGroup: typeof import('./components/ui/select/SelectGroup.vue')['default']
    SelectItem: typeof import('./components/ui/select/SelectItem.vue')['default']
    SelectItemText: typeof import('./components/ui/select/SelectItemText.vue')['default']
    SelectLabel: typeof import('./components/ui/select/SelectLabel.vue')['default']
    SelectScrollDownButton: typeof import('./components/ui/select/SelectScrollDownButton.vue')['default']
    SelectScrollUpButton: typeof import('./components/ui/select/SelectScrollUpButton.vue')['default']
    SelectSeparator: typeof import('./components/ui/select/SelectSeparator.vue')['default']
    SelectTrigger: typeof import('./components/ui/select/SelectTrigger.vue')['default']
    SelectValue: typeof import('./components/ui/select/SelectValue.vue')['default']
    Separator: typeof import('./components/ui/separator/Separator.vue')['default']
    Textarea: typeof import('./components/ui/textarea/Textarea.vue')['default']
    Tooltip: typeof import('./components/ui/tooltip/Tooltip.vue')['default']
    TooltipContent: typeof import('./components/ui/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./components/ui/tooltip/TooltipProvider.vue')['default']
    TooltipTrigger: typeof import('./components/ui/tooltip/TooltipTrigger.vue')['default']
  }
}

// For TSX support
declare global {
  const ArchiveCard: typeof import('./components/shared/archive/ArchiveCard.vue')['default']
  const ArchiveClient: typeof import('./components/shared/archive/ArchiveClient.vue')['default']
  const ArchiveGroup: typeof import('./components/shared/archive/ArchiveGroup.vue')['default']
  const Button: typeof import('./components/ui/button/Button.vue')['default']
  const Card: typeof import('./components/shared/archive/card.vue')['default']
  const Field: typeof import('./components/ui/field/Field.vue')['default']
  const FieldContent: typeof import('./components/ui/field/FieldContent.vue')['default']
  const FieldDescription: typeof import('./components/ui/field/FieldDescription.vue')['default']
  const FieldError: typeof import('./components/ui/field/FieldError.vue')['default']
  const FieldGroup: typeof import('./components/ui/field/FieldGroup.vue')['default']
  const FieldLabel: typeof import('./components/ui/field/FieldLabel.vue')['default']
  const FieldLegend: typeof import('./components/ui/field/FieldLegend.vue')['default']
  const FieldSeparator: typeof import('./components/ui/field/FieldSeparator.vue')['default']
  const FieldSet: typeof import('./components/ui/field/FieldSet.vue')['default']
  const FieldTitle: typeof import('./components/ui/field/FieldTitle.vue')['default']
  const Group: typeof import('./components/shared/archive/group.vue')['default']
  const HealthStatus: typeof import('./components/shared/health/HealthStatus.vue')['default']
  const Input: typeof import('./components/ui/input/Input.vue')['default']
  const Label: typeof import('./components/ui/label/Label.vue')['default']
  const Link: typeof import('./components/shared/Link.vue')['default']
  const Marquee: typeof import('./components/shared/Marquee.vue')['default']
  const MobileMenu: typeof import('./components/shared/navigation/MobileMenu.vue')['default']
  const RequestForm: typeof import('./components/shared/forms/RequestForm.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Select: typeof import('./components/ui/select/Select.vue')['default']
  const SelectContent: typeof import('./components/ui/select/SelectContent.vue')['default']
  const SelectGroup: typeof import('./components/ui/select/SelectGroup.vue')['default']
  const SelectItem: typeof import('./components/ui/select/SelectItem.vue')['default']
  const SelectItemText: typeof import('./components/ui/select/SelectItemText.vue')['default']
  const SelectLabel: typeof import('./components/ui/select/SelectLabel.vue')['default']
  const SelectScrollDownButton: typeof import('./components/ui/select/SelectScrollDownButton.vue')['default']
  const SelectScrollUpButton: typeof import('./components/ui/select/SelectScrollUpButton.vue')['default']
  const SelectSeparator: typeof import('./components/ui/select/SelectSeparator.vue')['default']
  const SelectTrigger: typeof import('./components/ui/select/SelectTrigger.vue')['default']
  const SelectValue: typeof import('./components/ui/select/SelectValue.vue')['default']
  const Separator: typeof import('./components/ui/separator/Separator.vue')['default']
  const Textarea: typeof import('./components/ui/textarea/Textarea.vue')['default']
  const Tooltip: typeof import('./components/ui/tooltip/Tooltip.vue')['default']
  const TooltipContent: typeof import('./components/ui/tooltip/TooltipContent.vue')['default']
  const TooltipProvider: typeof import('./components/ui/tooltip/TooltipProvider.vue')['default']
  const TooltipTrigger: typeof import('./components/ui/tooltip/TooltipTrigger.vue')['default']
}